//
// Generated file, do not edit! Created by nedtool 5.1 from routing/olsrpo/OLSRPOpkt.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __OLSRPOPKT_M_H
#define __OLSRPOPKT_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0501
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "OLSRPO_ETX_parameter.h"
#include "inet/networklayer/common/L3Address.h"
#include <string.h>
// }}

// cplusplus {{
#ifndef nsaddr_t
typedef inet::L3Address nsaddr_t;
#endif

/********** Message types **********/
/// %OLSRPO HELLO message type.
#define OLSRPO_HELLO_MSG      1
/// %OLSRPO TC message type.
#define OLSRPO_TC_MSG     2
/// %OLSRPO MID message type.
#define OLSRPO_MID_MSG        3


/// %OLSRPO HELLO message type.
#define OLSRPO_ETX_HELLO_MSG  OLSRPO_HELLO_MSG
/// %OLSRPO TC message type.
#define OLSRPO_ETX_TC_MSG     OLSRPO_TC_MSG
/// %OLSRPO MID message type.
#define OLSRPO_ETX_MID_MSG    OLSRPO_MID_MSG

/********** Packets stuff **********/

///
/// \brief Size of the addresses we are using.
///
/// You should always use this macro when interested in calculate addresses'
/// sizes. By default IPv4 addresses are supposed, but you can change to
/// IPv6 ones by recompiling with OLSRPO_IPv6 constant defined.
///

#ifdef OLSRPO_IPv6
#define ADDR_SIZE_DEFAULT   16
#else
#define ADDR_SIZE_DEFAULT   4
#endif

class OlsrAddressSize
{
    public:
    static uint32_t ADDR_SIZE;
};

/// Maximum number of messages per packet.
#define OLSRPO_MAX_MSGS       4
#define OLSRPO_ETX_MAX_MSGS OLSRPO_MAX_MSGS
/// Maximum number of hellos per message (4 possible link types * 3 possible nb types).
#define OLSRPO_MAX_HELLOS     12
#define OLSRPO_ETX_MAX_HELLOS OLSRPO_MAX_HELLOS
/// Maximum number of addresses advertised on a message.
#define OLSRPO_MAX_ADDRS      64
#define OLSRPO_ETX_MAX_ADDRS OLSRPO_MAX_ADDRS

/// Size (in bytes) of packet header.
#define OLSRPO_PKT_HDR_SIZE   4
#define OLSRPO_ETX_PKT_HDR_SIZE OLSRPO_PKT_HDR_SIZE

/// Size (in bytes) of message header.
#define OLSRPO_MSG_HDR_SIZE   8 + OlsrAddressSize::ADDR_SIZE
#define OLSRPO_ETX_MSG_HDR_SIZE OLSRPO_MSG_HDR_SIZE

/// Size (in bytes) of hello header.
#define OLSRPO_HELLO_HDR_SIZE 4
#define OLSRPO_ETX_HELLO_HDR_SIZE OLSRPO_HELLO_HDR_SIZE

/// Size (in bytes) of hello_msg header.
#define OLSRPO_HELLO_MSG_HDR_SIZE 4
#define OLSRPO_ETX_HELLO_MSG_HDR_SIZE OLSRPO_HELLO_MSG_HDR_SIZE

/// Size (in bytes) of tc header.
#define OLSRPO_TC_HDR_SIZE    4
#define OLSRPO_ETX_TC_HDR_SIZE OLSRPO_TC_HDR_SIZE


typedef struct OLSRPO_ETX_iface_address {

  /// Interface Address
  nsaddr_t  iface_address_;

  /// Link quality extension
  double  link_quality_;
  double  nb_link_quality_;

  /// Link delay extension
  double  link_delay_;
  double  nb_link_delay_;
  int parameter_qos_;

  inline nsaddr_t& iface_address() { return iface_address_; }

  /// Link quality extension
  inline double& link_quality() { return link_quality_; }
  inline double& nb_link_quality() { return nb_link_quality_; }

  inline double  etx()  {
    double mult = (double) (link_quality() * nb_link_quality());
    switch (parameter_qos_) {
    case OLSRPO_ETX_BEHAVIOR_ETX:
      return (mult < 0.01) ? 100.0 : (double) 1.0 / (double) mult;
      break;

    case OLSRPO_ETX_BEHAVIOR_ML:
      return mult;
      break;

    case OLSRPO_ETX_BEHAVIOR_NONE:
    default:
      return 0.0;
      break;
    }
  }

  /// Link delay extension
  inline double& link_delay() { return link_delay_; }
  inline double& nb_link_delay() { return nb_link_delay_; }

} OLSRPO_ETX_iface_address;


/// Auxiliary struct which is part of the %OLSRPO_ETX HELLO message (struct OLSRPO_ETX_hello).
typedef struct OLSRPO_hello_msg {

  /// Link code.
  uint8_t  link_code_;
  /// Reserved.
  uint8_t  reserved_;
  /// Size of this link message.
  uint16_t  link_msg_size_;
  /// List of interface addresses of neighbor nodes.
  OLSRPO_ETX_iface_address  nb_iface_addrs_[OLSRPO_MAX_ADDRS];
  /// Number of interface addresses contained in nb_iface_addrs_.
  int    count;

  inline uint8_t&  link_code()    { return link_code_; }
  inline uint8_t&  reserved()    { return reserved_; }
  inline uint16_t&  link_msg_size()    { return link_msg_size_; }
  inline OLSRPO_ETX_iface_address&  nb_etx_iface_addr(int i)  { return nb_iface_addrs_[i]; }
  inline nsaddr_t  & nb_iface_addr(int i)  { return nb_iface_addrs_[i].iface_address_;}
  inline void set_qos_behaviour(int bh) {for(int i=0;i<OLSRPO_MAX_ADDRS;i++) nb_iface_addrs_[i].parameter_qos_=bh;}

  inline uint32_t size() { return OLSRPO_HELLO_MSG_HDR_SIZE + count*OlsrAddressSize::ADDR_SIZE; }

} OLSRPO_ETX_hello_msg;

#if 0
/// Auxiliary struct which is part of the %OLSRPO HELLO message (struct OLSRPO_hello).
typedef struct OLSRPO_hello_msg {

        /// Link code.
    uint8_t link_code_;
    /// Reserved.
    uint8_t reserved_;
    /// Size of this link message.
    uint16_t    link_msg_size_;
    /// List of interface addresses of neighbor nodes.
    nsaddr_t    nb_iface_addrs_[OLSRPO_MAX_ADDRS];
    /// Number of interface addresses contained in nb_iface_addrs_.
    int     count;

    inline uint8_t& link_code()     { return link_code_; }
    inline uint8_t& reserved()      { return reserved_; }
    inline uint16_t&    link_msg_size()     { return link_msg_size_; }
    inline nsaddr_t&    nb_iface_addr(int i)    { return nb_iface_addrs_[i]; }

    inline uint32_t size() { return OLSRPO_HELLO_MSG_HDR_SIZE + count*OlsrAddressSize::ADDR_SIZE; }

} OLSRPO_hello_msg;
#endif

/// %OLSRPO HELLO message.

typedef struct OLSRPO_hello :cObject {

    /// Reserved.
    uint16_t    reserved_;
    /// HELLO emission interval in mantissa/exponent format.
    uint8_t htime_;
    /// Willingness of a node for forwarding packets on behalf of other nodes.
    uint8_t willingness_;
    /// List of OLSRPO_hello_msg.
    OLSRPO_hello_msg  hello_body_[OLSRPO_MAX_HELLOS];
    /// Number of OLSRPO_hello_msg contained in hello_body_.
    int     count;

    inline uint16_t&    reserved()      { return reserved_; }
    inline uint8_t& htime()         { return htime_; }
    inline uint8_t& willingness()       { return willingness_; }
    inline OLSRPO_hello_msg&  hello_msg(int i)    { return hello_body_[i]; }

    inline uint32_t size() {
        uint32_t sz = OLSRPO_HELLO_HDR_SIZE;
        for (int i = 0; i < count; i++)
            sz += hello_msg(i).size();
        return sz;
    }
} OLSRPO_hello;


/// %OLSRPO TC message.
typedef struct OLSRPO_tc :cObject{

        /// Advertised Neighbor Sequence Number.
    uint16_t    ansn_;
    /// Reserved.
    uint16_t    reserved_;
    /// List of neighbors' main addresses.
    OLSRPO_ETX_iface_address  nb_main_addrs_[OLSRPO_MAX_ADDRS];
    /// Number of neighbors' main addresses contained in nb_main_addrs_.
    int     count;

    inline  uint16_t&   ansn()          { return ansn_; }
    inline  uint16_t&   reserved()      { return reserved_; }
    inline  nsaddr_t&   nb_main_addr(int i) { return nb_main_addrs_[i].iface_address_; }
    inline  OLSRPO_ETX_iface_address& nb_etx_main_addr(int i) { return nb_main_addrs_[i]; }
    inline void set_qos_behaviour(int bh) {for(int i=0;i<OLSRPO_MAX_ADDRS;i++) nb_main_addrs_[i].parameter_qos_=bh;}
    inline  uint32_t size() { return OLSRPO_TC_HDR_SIZE + count*OlsrAddressSize::ADDR_SIZE; }
} OLSRPO_tc;

#if 0
/// %OLSRPO TC message.
typedef struct OLSRPO_tc :cObject{

        /// Advertised Neighbor Sequence Number.
    uint16_t    ansn_;
    /// Reserved.
    uint16_t    reserved_;
    /// List of neighbors' main addresses.
    nsaddr_t    nb_main_addrs_[OLSRPO_MAX_ADDRS];
    /// Number of neighbors' main addresses contained in nb_main_addrs_.
    int     count;

    inline  uint16_t&   ansn()          { return ansn_; }
    inline  uint16_t&   reserved()      { return reserved_; }
    inline  nsaddr_t&   nb_main_addr(int i) { return nb_main_addrs_[i]; }

    inline  uint32_t size() { return OLSRPO_TC_HDR_SIZE + count*OlsrAddressSize::ADDR_SIZE; }

} OLSRPO_tc;
#endif

/// %OLSRPO MID message.
typedef struct OLSRPO_mid :cObject{

    /// List of interface addresses.
    nsaddr_t    iface_addrs_[OLSRPO_MAX_ADDRS];
    /// Number of interface addresses contained in iface_addrs_.
    int     count;

    inline nsaddr_t & iface_addr(int i) { return iface_addrs_[i]; }
    void    setIface_addr(int i,nsaddr_t a) {iface_addrs_[i]=a; }

    inline uint32_t size()          { return count*OlsrAddressSize::ADDR_SIZE; }

} OLSRPO_mid;

#define MidSize sizeof (OLSRPO_mid)
#define HelloSize sizeof (OLSRPO_hello)
#define TcSize sizeof(OLSRPO_tc)

#define MAXBODY (HelloSize > TcSize ?  (HelloSize > MidSize? HelloSize: MidSize):(TcSize > MidSize? TcSize:MidSize))


class   MsgBody {
public:
    OLSRPO_hello  hello_;
    OLSRPO_tc     tc_;
    OLSRPO_mid    mid_;


    MsgBody(MsgBody &other){
            memcpy((void*)&hello_,(void*)&other.hello_,sizeof(OLSRPO_hello));
            memcpy((void*)&tc_,(void*)&other.tc_,sizeof(OLSRPO_tc));
            memcpy((void*)&mid_,(void*)&other.mid_,sizeof(OLSRPO_mid));
        }
    MsgBody(){
            memset((void*)&hello_,0,sizeof(OLSRPO_hello));
            memset((void*)&tc_,0,sizeof(OLSRPO_tc));
            memset((void*)&mid_,0,sizeof(OLSRPO_mid));
          }
    ~MsgBody(){}
    MsgBody & operator =  (const MsgBody &other){
            if (this==&other) return *this;
                            memcpy((void*)&hello_,(void*)&other.hello_,sizeof(OLSRPO_hello));
                            memcpy((void*)&tc_,(void*)&other.tc_,sizeof(OLSRPO_tc));
                            memcpy((void*)&mid_,(void*)&other.mid_,sizeof(OLSRPO_mid));
                return *this;
            }
    OLSRPO_hello  * hello(){return &hello_;}
    OLSRPO_tc * tc(){return &tc_;}
    OLSRPO_mid* mid(){return &mid_;}


};

/// %OLSRPO message.
typedef struct OLSRPO_msg {

    uint8_t msg_type_;  ///< Message type.
    uint8_t vtime_;     ///< Validity time.
    uint16_t    msg_size_;  ///< Message size (in bytes).
    nsaddr_t    orig_addr_; ///< Main address of the node which generated this message.
    uint8_t ttl_;       ///< Time to live (in hops).
    uint8_t hop_count_; ///< Number of hops which the message has taken.
    uint16_t    msg_seq_num_;   ///< Message sequence number.

    MsgBody msg_body_;          ///< Message body.
    inline  uint8_t&    msg_type()  { return msg_type_; }
    inline  uint8_t&    vtime()     { return vtime_; }
    inline  uint16_t&   msg_size()  { return msg_size_; }
    inline  nsaddr_t    & orig_addr()   { return orig_addr_; }
    inline  void    setOrig_addr(nsaddr_t a)    {orig_addr_=a; }
    inline  uint8_t&    ttl()       { return ttl_; }
    inline  uint8_t&    hop_count() { return hop_count_; }
    inline  uint16_t&   msg_seq_num()   { return msg_seq_num_; }
    inline  OLSRPO_hello& hello()     { return *(msg_body_.hello()); }
    inline  OLSRPO_tc&    tc()        { return *(msg_body_.tc()); }
    inline  OLSRPO_mid&   mid()       { return *(msg_body_.mid()); }


    inline uint32_t size() {
        uint32_t sz = OLSRPO_MSG_HDR_SIZE;
        if (msg_type() == OLSRPO_HELLO_MSG)
            sz += hello().size();
        else if (msg_type() == OLSRPO_TC_MSG)
            sz += tc().size();
        else if (msg_type() == OLSRPO_MID_MSG)
            sz += mid().size();
        return sz;
    }
    OLSRPO_msg(){}
    OLSRPO_msg(const OLSRPO_msg &other)
    {
        msg_type_=other.msg_type_;  ///< Message type.
        vtime_=other.vtime_;        ///< Validity time.
        msg_size_=other.msg_size_;  ///< Message size (in bytes).
        orig_addr_=other.orig_addr_;    ///< Main address of the node which generated this message.
        ttl_=other.ttl_;        ///< Time to live (in hops).
        hop_count_=other.hop_count_;    ///< Number of hops which the message has taken.
        msg_seq_num_=other.msg_seq_num_;    ///< Message sequence number.
        msg_body_=other.msg_body_;          ///< Message body.
    }

    OLSRPO_msg & operator = (const OLSRPO_msg &other)
    {
        if (this==&other) return *this;
        msg_type_=other.msg_type_;  ///< Message type.
        vtime_=other.vtime_;        ///< Validity time.
        msg_size_=other.msg_size_;  ///< Message size (in bytes).
        orig_addr_=other.orig_addr_;    ///< Main address of the node which generated this message.
        ttl_=other.ttl_;        ///< Time to live (in hops).
        hop_count_=other.hop_count_;    ///< Number of hops which the message has taken.
        msg_seq_num_=other.msg_seq_num_;    ///< Message sequence number.
        msg_body_=other.msg_body_;          ///< Message body.
        return *this;
    }

} OLSRPO_msg;
// }}

/**
 * Class generated from <tt>routing/olsrpo/OLSRPOpkt.msg:406</tt> by nedtool.
 * <pre>
 * //
 * // Represents an OLSRPO packet
 * //
 * // Uses the following cMessage fields:
 * //    - length () / setLength(err)  in bits
 * //    - hasBitError() / setBitError()
 * //    - timestamp() / setTimestamp (simtime) used in timestamp option
 * //
 * // Additional length fields defined in this class are in bytes
 * // (totalLength()=length()/8 and header_length), or 8 bytes (fragment_offset).
 * //
 * // Only one of the option fields can exist at a time.
 * //
 * packet OLSRPO_pkt
 * {
 *     \@omitGetVerb(true);
 *     bool reduceFuncionality = false;
 *     short pkt_seq_num;          ///< Packet sequence number.
 *     long sn;                    /// CapProbe packet sequence number
 *     double send_time;           /// Packet sending timestamp
 *     OLSRPO_msg msg[];             ///< Packet body.
 * }
 * </pre>
 */
class OLSRPO_pkt : public ::omnetpp::cPacket
{
  protected:
    bool reduceFuncionality_var;
    short pkt_seq_num_var;
    long sn_var;
    double send_time_var;
    OLSRPO_msg *msg_var; // array ptr
    unsigned int msg_arraysize;

  private:
    void copy(const OLSRPO_pkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OLSRPO_pkt&);

  public:
    OLSRPO_pkt(const char *name=nullptr, short kind=0);
    OLSRPO_pkt(const OLSRPO_pkt& other);
    virtual ~OLSRPO_pkt();
    OLSRPO_pkt& operator=(const OLSRPO_pkt& other);
    virtual OLSRPO_pkt *dup() const override {return new OLSRPO_pkt(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual bool reduceFuncionality() const;
    virtual void setReduceFuncionality(bool reduceFuncionality);
    virtual short pkt_seq_num() const;
    virtual void setPkt_seq_num(short pkt_seq_num);
    virtual long sn() const;
    virtual void setSn(long sn);
    virtual double send_time() const;
    virtual void setSend_time(double send_time);
    virtual void setMsgArraySize(unsigned int size);
    virtual unsigned int msgArraySize() const;
    virtual OLSRPO_msg& msg(unsigned int k);
    virtual const OLSRPO_msg& msg(unsigned int k) const {return const_cast<OLSRPO_pkt*>(this)->msg(k);}
    virtual void setMsg(unsigned int k, const OLSRPO_msg& msg);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const OLSRPO_pkt& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, OLSRPO_pkt& obj) {obj.parsimUnpack(b);}


#endif // ifndef __OLSRPOPKT_M_H

