#!/bin/sh
cd `dirname $0`
mkdir ../simulations/logs > /dev/null 2>&1
CPUCOUNT=$(cat /proc/cpuinfo  | grep processor | wc -l)
if [[ $2 =~ "verbose" ]]; then
  echo
  echo "switching to single thread mode (verbose)"
  CPUCOUNT=1
else
  echo
  echo "running with $CPUCOUNT threads"
fi

case $1 in

aodv)

echo
echo "running AODV/AODVPO simulations, please wait ..."
echo
for i in $(grep "\[Config " aodv.ini | cut -d " " -f 2 | cut -d "]" -f 1); do
  while [ $(ps aux | grep opp | grep -v grep | wc -l) -ge $CPUCOUNT ]; do sleep 1; done  
  echo "  configuration: $i (log: logs/$i.log)"
  if [[ $2 =~ "verbose" ]]; then
    opp_run.exe -r 0 -m -u Cmdenv \
      -n "../src;../simulations;../../inet/examples;../../inet/showcases;../../inet/src;../../inet/tutorials" --image-path=../../inet/images \
      -l ../src/powerrouting -l ../../inet/src/INET \
      -c $i ../simulations/aodv.ini 2>&1 | tee logs/$i.log &
  else
    opp_run.exe -r 0 -m -u Cmdenv \
      -n "../src;../simulations;../../inet/examples;../../inet/showcases;../../inet/src;../../inet/tutorials" --image-path=../../inet/images \
      -l ../src/powerrouting -l ../../inet/src/INET \
      -c $i ../simulations/aodv.ini > logs/$i.log 2>&1 &
  fi
done
echo
echo "AODV/AODVPO simulations done."
echo

;;
olsr)

echo
echo "running OLSR/OLSRPO simulations, please wait ..."
echo
for i in $(grep "\[Config " olsr.ini | cut -d " " -f 2 | cut -d "]" -f 1); do
  while [ $(ps aux | grep opp | grep -v grep | wc -l) -ge $CPUCOUNT ]; do sleep 1; done  
  echo "  configuration: $i (log: logs/$i.log)"
  if [[ $2 =~ "verbose" ]]; then
    opp_run.exe -r 0 -m -u Cmdenv \
      -n "../src;../simulations;../../inet/examples;../../inet/showcases;../../inet/src;../../inet/tutorials" --image-path=../../inet/images \
      -l ../src/powerrouting -l ../../inet/src/INET \
      -c $i ../simulations/olsr.ini 2>&1 | tee logs/$i.log &
  else
    opp_run.exe -r 0 -m -u Cmdenv \
      -n "../src;../simulations;../../inet/examples;../../inet/showcases;../../inet/src;../../inet/tutorials" --image-path=../../inet/images \
      -l ../src/powerrouting -l ../../inet/src/INET \
      -c $i ../simulations/olsr.ini > logs/$i.log 2>&1 &
   fi
done
echo
echo "OLSR/OLSRPO simulations done."
echo

;;

all)

$0 aodv $2
$0 olsr $2

;;

*)

echo
echo "usage: ./run [mode] (verbose)"
echo "  runs designated tests and logs to files (multihreaded),"
echo "  for logging to screen and files, append 'verbose' (only singlethreaded)"
echo
echo "  modes:"
echo "  all - run all simulations"
echo "  olsr - run olsr simulations"
echo "  aodv - run aodv simulations"
echo "  help - print this help"
echo

;;

esac